### ISSUE TITLE
expected-return sometimes not found

### ISSUE THREAD

**Issue by mchugh19** [wcannon/salt-check#14]
This might just be a local problem, but I have a test that seems to get detected as not valid, and I'm not exactly sure why. 

Using this check for boto doesn't seem to work:
```
boto-installed:
  module_and_function: cmd.run
  args:
    - python -c 'import pkgutil; print(1 if pkgutil.find_loader("boto") else 0)'
  assertion: assertNotEqual
  expected-return: 0
```
and returns
```
    [INFO    ] __is_valid_test has test: {u'expected-return': 0, u'module_and_function': u'cmd.run', u'args': [u'python -c \'import pkgutil; print(1 if pkgutil.find_loader("boto3") else 0)\''], u'assertion': u'assertNotEqual'}
    [INFO    ] __is_valid_test has valid m_and_f
    [INFO    ] __is_valid_test has valid_assertion
    [INFO    ] __is_valid_test score: 5
```

I'm not sure if there's something going on with an expected-return value 0 that makes it unreadable or something, because reversing it work just fine.
```
boto-installed:
  module_and_function: cmd.run
  args:
    - python -c 'import pkgutil; print(1 if pkgutil.find_loader("boto") else 0)'
  assertion: assertEqual
  expected-return: 1
```

**Comment by wcannon** [comment]
I believe you already solved this one.

The test for an expected-return value is using python True|False evaluation.

Therefore, 0 == False.

If you put quotes around the 0 I believe this will solve the issue.  Alternatively, we could consider changing the evaluation to checking the expected-return in a different way.

What do you suggest?

**Comment by wcannon** [comment]
I just rewrote this function.  (__is_valid_test) to make it more clear and optional to include the "expected-return" key in a more obvious way.   The original way I wrote this was getting a little convoluted.  

Sorry about rejecting the pull request.  I really felt like it would be better to rewrite the whole function.  Your suggestion was very good.  Please keep the good ideas coming!
