### ISSUE TITLE
rspec-puppet to salt-check transition

### ISSUE THREAD

**Issue by gerases** [wcannon/salt-check#18]
I come from the world of puppet. Puppet has a test suite called `rspec-puppet`, which is based on a more general ruby testing framework called `rspec`. With `rspec-puppet`, one is able to:

* Test a module being completely outside of the production environment.
* Mock any input data such as an IP, OS, or anything else
* Run tests without any side effects. That is, if I have a command that removes everything under a directory, it won't actually get executed, but you can still see that it would have been run.

Is salt-check similar? For example, if i had a command like this `rm -rf /` and tried to test it on a minion, would it actually get executed?

**Comment by wcannon** [comment]
I'll try to give you a few insights on saltcheck.

Saltcheck can be run either in stand-alone mode (minion without master), or in standard mode (minion with master).
All the functionality of salt execution modules are available for saltcheck tests.  And, they can make changes to the system.  So, the responsibility to not make changes lies with the user.
The objective of saltcheck is to allow for easy and non-fragile end-state testing of a server.  Non-fragile means that the targeting of a server (and all salt cli options) work with saltcheck.  Essentially this means one can test either one, several or all states that make up a highstate against a server.  A nice example here is the command to run all tests for states that make up a highstate.

Please let me know if you have more questions.
