### ISSUE TITLE
Ability to generate junit test report

### ISSUE THREAD

**Issue by dawidmalina** [wcannon/salt-check#24]
I'm really impressed your presentation and we were looking for simple but powerful unit test framework for our salt states and looks like we found it:)

The only think we are missing right now it ability to generate cumulated test result in file with one of the unit test standard xunit or junit to be able to import test report in our CI (jenkins in our case).

I belive that more people could be interested in such feature.

**Comment by wcannon** [comment]
Thanks.  I'm glad you find saltcheck useful.  

At the moment saltcheck (from this repo) is broken for 2018.3 salt open, which I'll be fixing soon.  However, the version that saltstack merged into salt open (2018.3) is working.

What you suggested sounds very useful to the CI / CD users.  Do you have any approaches that might make this easy or straight-forward to do?  I have not tried to integrate with CI test standard formats before.  Would a custom salt renderer work?

**Comment by dawidmalina** [comment]
What i would like to have is exactly CI / CD pipeline with quality stage where we will perform unit tests for all existing (or missed) states in our repo containing all different saltstack states which configure our hosts.

I know a bit python but not as much to propose some code modifycations but this can be used as example: https://pypi.org/project/junit-xml/

**Comment by dawidmalina** [comment]
Btw I checked the commits as i could believe :D great that this will be part of salt open 👍

**Comment by dawidmalina** [comment]
OK. I was able to properly generate junit output with custom output script.

```
salt-call -l warning saltcheck.run_highstate_tests --out junit
```
```
<testsuite errors="0" failures="3" name="Saltcheck state(s) junit tests resultss" skipped="1" tests="6">
<testcase classname="state.apache" name="example-test-4-md5sum"><failure>Fail: True is not equal to False</failure></testcase>
<testcase classname="state.apache" name="example-test-3-/tmp/hello"><failure>Fail: True is not equal to False</failure></testcase>
<testcase classname="state.apache" name="example-test-2-hellos"><failure>Fail: hello is not equal to hellos</failure></testcase>
<testcase classname="state.apache" name="example-test-1-hello" />
<testcase classname="state.nothing" name="Undefined"><skipped /></testcase>
<testcase classname="state.nothing.sub" name="correct-version-net-tools-installed" />
</testsuite>
```

Here is the simple python code that i used:
```
# -*- coding: utf-8 -*-

import logging
import yaml
import xml.etree.ElementTree as xml
log = logging.getLogger(__name__)

def _text_node(name, text=None):
    element = xml.Element(name)
    if text:
        element.text = text
    return element

def _test_case(classname, name, time=False):
    element = xml.Element('testcase')
    element.attrib['name'] = name
    element.attrib['classname'] = classname
    if time is not False:
        element.attrib['time'] = time
    return element

def output(data):
    root = xml.Element('testsuite')
    for d in data:
      output = data[d]
      for o in output:
        for k in o:
          results = o[k]
          if k == 'TEST RESULTS':
            root.attrib['name'] = 'Saltcheck state(s) junit tests resultss'
            root.attrib['errors'] = '0'
            root.attrib['failures'] = str(results['Failed'])
            root.attrib['skipped'] = str(results['Missing Tests'])
            root.attrib['tests'] = str(results['Passed'] + results['Failed'] + results['Missing Tests'])
          else:
            if len(results) == 0:
                test_case_element = _test_case(('state.' + k), 'Undefined')
                skipped_element = _text_node('skipped')
                test_case_element.append(skipped_element)
                root.append(test_case_element)
            else:
              for case in results:
                result = results[case]
                if result == 'Pass':
                    test_case_element = _test_case(('state.' + k), case)
                    root.append(test_case_element)
                else:
                    test_case_element = _test_case(('state.' + k), case)
                    failure_element = _text_node('failure', result)
                    test_case_element.append(failure_element)
                    root.append(test_case_element)

    return xml.tostring(root)
```

The test report generated in Jenkins looks like this:
<img width="1075" alt="zrzut ekranu 2018-04-23 o 20 09 02" src="https://user-images.githubusercontent.com/5910851/39144865-618c4d34-4732-11e8-927b-88100f2a5569.png">

@wcannon if you think the code is ok i can drop a pull request.

**Comment by dawidmalina** [comment]
Thx

**Comment by wcannon** [comment]
Thanks for all the pull requests!

At some point I'd like to set up some automated jenkins tests too
(pre-merge).

On Sun, May 13, 2018 at 12:31 PM, Dawid Malinowski <notifications@github.com

**Comment by dawidmalina** [comment]
@wcannon you can find simple jenkins pipeline here https://github.com/wcannon/salt-check/pull/33
