### ISSUE TITLE
Add setup and teardown option

### ISSUE THREAD

**Issue by dawidmalina** [wcannon/salt-check#27]
It would be nice to have setup and teardown option where you could execute for example state.apply just before test execution and some kind of cleanup just after test execution.

**Comment by wcannon** [comment]
You are burning through these!

My thoughts on what I believe you are trying to accomplish would be to
implement the following:
1 - an alternate pillar injected at test time (state/highstate).  I imagine
this could be done on the command line as a parameter e.g. a json string
2 - ability to designate a set of tests outside of a state.  Essentially,
the idea here is to keep the same test lookup / compilation structure but
not have to have the tests as a subdir of a salt state dir.  For this I am
imagining a command line parameter to name the dir(s) [like
/srv/salt/tests/scenario1, /srv/salt/tests/scenario2] to search for tests

I believe that having these two capabilities would open up a lot more
flexibility for testing.
- injectable pillar
- tests outside of salt state dir

What do you think?

**Comment by dawidmalina** [comment]
For now i think we can close this ticket.
