### ISSUE TITLE
How many people are using saltcheck?

### ISSUE THREAD

**Issue by wcannon** [wcannon/salt-check#36]
Any idea how to find out?  Would very much like to know.

**Comment by justin-sunayu** [comment]
I'd like to start using it more regularly but several issues are keeping me from doing so:
* The issues with 2018.3.0. I feel like this release is still very buggy and have not started using it yet.
* Compatability with 2017.7.x. I tried running the latest saltcheck from this repo and get different errors depending on when I try and use it. I guess I am waiting for a stable salt release with a stable saltcheck.

**Comment by claudekenni** [comment]
Kudos to you, this module is awesome. 
After some first struggles to figure some things out I can now fly through and create tests for my states.

The documentation needs some work, it is really scattered in multiple places.

**Comment by dawidmalina** [comment]
We've are started to using it after our's small contributions (changes) and now we are quite happy with our unit tests. We've are started to using it after our small contributions (changes) and now we are quite happy with our unit tests. But i must admit we have our patches applied on saltstack.py from 2018.3.0 not from this repo.

@justin-sunayu what kind of issues do you have?

**Comment by justin-sunayu** [comment]
See https://github.com/wcannon/salt-check/issues/22

**Comment by wcannon** [comment]
Thanks for the info.
