### ISSUE TITLE
Nested states in formulas and missing saltcheck tests

### ISSUE THREAD

**Issue by justin-sunayu** [wcannon/salt-check#37]
I have the following test formula:

```[root@sm ttest]# pwd
/srv/saltstack/formulas/ttest
[root@sm ttest]# find .
.
./saltcheck-tests
./saltcheck-tests/test_1.tst
./saltcheck-tests/dirone
./saltcheck-tests/dirone/init.tst
./dirone
./dirone/init.sls
./dirone/config.sls
./dirtwo
./dirtwo/init.sls
./dirtwo/config.sls
./fileone.sls
./nesteddir
./nesteddir/nesteddirdir
./nesteddir/nesteddirdir/nesteddirdirthing.sls
./nesteddir/nesteddirdir/init.sls
./nesteddir/init.sls
./init.sls
```

When I run it I get the following:

```c71:
    |_
      ----------
      ttest:
          ----------
          example-test:
              ----------
              duration:
                  0.6451
              status:
                  Fail: 12345 is not equal to  16:25:02 up 9 days, 19:24,  0 users,  load average: 0.56, 0.33, 0.27
    |_
      ----------
      ttest.dirone:
          ----------
    |_
      ----------
      ttest.dirone.config:
          ----------
    |_
      ----------
      ttest.dirtwo:
          ----------
    |_
      ----------
      ttest.dirtwo.config:
          ----------
    |_
      ----------
      ttest.fileone:
          ----------
    |_
      ----------
      ttest.nesteddir:
          ----------
    |_
      ----------
      ttest.nesteddir.nesteddirdir:
          ----------
    |_
      ----------
      ttest.nesteddir.nesteddirdir.nesteddirdirthing:
          ----------
    |_
      ----------
      TEST RESULTS:
          ----------
          Execution Time:
              0.6451
          Failed:
              1
          Missing Tests:
              8
          Passed:
              0
          Skipped:
              0
```

It is only running the test located in ./saltcheck-tests/dirone/init.tst yet it also shows it as missing?

What would be the correct way to go about laying out test files for a formula as complex as this?

**Comment by dawidmalina** [comment]
With the current implementation it will not be possible to do what you are looking for as test folder must be inside independent state or substate. We have also quite complex states and substates structure but we are using structure as follow (just an example):
```
stateA/init.sls
stateA/saltcheck-tests/stateA-default.tst
stateA/sub-stateB/init.sls
stateA/sub-stateB/saltcheck-tests/sub-stateB-default.tst
stateA/sub-stateB/sub-stateC/init.sls
stateA/sub-stateB/sub-stateC/saltcheck-tests/sub-stateC-default.tst
```

I know that maybe it's generates a lot of folders but at least it's clean in my opinion.

**Comment by wcannon** [comment]
It sounds like there is a need for a different way to designate tests to go along with states.  Could you @dawidmalina or @justin-sunayu  give me the ideal way to designate tests for your use cases?

fyi: The original idea was to be explicit and even a bit opinionated.  But, I'm leaning for a solution that keeps a simple default that would work for 80 - 90% of the use cases, with the flexibility for power users to achieve more complex / flexible use cases.

**Comment by dawidmalina** [comment]
In our case 99.9% states are within dedicated folders or subfolders:) and we are happy about this. But if we could have tests not strictly related to folder structure we could use it for more complicated tests aka integration tests. But i must admit for this we started to use pure python and bdd framwork.

**Comment by justin-sunayu** [comment]
Thanks @dawidmalina for some reason that didn't occur to me. That works for my use case! Thanks
