### ISSUE TITLE
assertEmpty / assertNotEmpty

### ISSUE THREAD

**Issue by wcannon** [wcannon/salt-check#6]
from mchugh19

Description of Issue/Question

Some salt modules such as pkg.latest_version (yum) produce no output. For that module, it will output either the latest version number of the available package, or no output if the package is up to date.
Thus the saltcheck test to verify if a package is at the latest version could read as:

openssh-server-latest:
  module_and_function: pkg.latest_version
  args:
    - openssh-server
  kwargs:
  assertion: assertEqual
  expected-return: ""
But when running this test, it fails due to the lack of an expected return.

So perhaps the expected return check could be disabled as sometimes this is expected, or an assertEmpty assertion could be introduced which would selectively disable the expected-return check.

**Comment by wcannon** [comment]
Will implement assertEmpty / assertNotEmpty to handle these cases

**Comment by wcannon** [comment]
done - needs some more testing though....

**Comment by mchugh19** [comment]
Looks like the internal validation check isn't happy with assertEmpty...
```
    [INFO    ] __is_valid_test has valid m_and_f
    [INFO    ] __is_valid_test has valid_assertion
    [INFO    ] __is_valid_test score: 5
    [INFO    ] dummy=openssh-server-latest, val=Fail - invalid test```

**Comment by wcannon** [comment]
Hmmm...can you send me the test block you used?

At the moment, even though it seems silly the validator for the test block
expects a value in the expected-return.



On Mon, Nov 13, 2017 at 10:41 AM, Christian McHugh <notifications@github.com

**Comment by wcannon** [comment]
ok, that is probably the issue.

Add in a line for:
   expected-return: ''

This should fix the issue.  But, we need to rethink if / how to validate a
test block is valid.  Salt doesn't do this.  But, I like the idea of
catching the error and alerting the user - more friendly, easier to fix....

What do you think?

On Mon, Nov 13, 2017 at 10:50 AM, Christian McHugh <notifications@github.com

**Comment by mchugh19** [comment]
No problem added the expected-return line. But this should likely be worked around in the case of assertEmpty or assertNotEmpty.

**Comment by wcannon** [comment]
Yes, agree with you on that.   In addition, assertTrue and assertFalse
should not need the expected-return key to have a value either.

I'm open to suggestions.

On Mon, Nov 13, 2017 at 11:08 AM, Christian McHugh <notifications@github.com

**Comment by mchugh19** [comment]
Took a crack in #8  (didn't tackle the assertTrue or assertFalse)
