### ISSUE TITLE
Deleted tests remain after running update_master_cache

### ISSUE THREAD

**Issue by mchugh19** [wcannon/salt-check#7]
When test is written, and the tst file later deleted, it still remains active and in the minion cache. A more robust update_master_cache operation may be necessary to remove old tests.

**Comment by wcannon** [comment]
Can you give me a step-by-step list to reproduce the issue?

I'm wondering if you are issuing an update_master_cache call after deleting the tst file.

**Comment by mchugh19** [comment]
In our environment, we have many formulas contained in gitfs repos, including openssh. We created the saltcheck-tests directory in that git repo, and added a .tst file inside. Then there were some experimental tests we wanted to write, but were not quite sure about the syntax. So we created /srv/salt/openssh/saltcheck-tests and added a testing .tst file inside. Once we were happy with that test, we then rm -r'ed /srv/salt/openssh/saltcheck-tests. This left the cached file on our host, and it persisted after running the update_master_cache.

**Comment by wcannon** [comment]
Great info - thanks!  I thought calling update_master_cache would have worked (between saltcheck runs).  saltcheck.update_master_cache actually calls the salt module/function cp.cache_master (see below for what it does).  I'm going to have to do a bit of testing to narrow down where this is failing to clear out old tests.  

"""
salt.modules.cp.cache_master(saltenv='base')
Retrieve all of the files on the master and cache them locally
"""

**Comment by wcannon** [comment]
This was a really nice bug to fix.  The fix should obviate the need for the update_master_cache function.  Essentially, every state / highstate test run will always refresh the test files from the master.

I did some limited testing on this (using centos7) to simulate your environment.  But, I'm not using gitfs.  Please give this a few rounds of testing and let me know what you find.

**Comment by mchugh19** [comment]
Looks good. I'll test over the next few days. 

What is the logic used for saltutul.sync_modules? It would be nice if we didn't need to clobber the cache on every run and only delete missing files.

**Comment by wcannon** [comment]
I'm not sure exactly what salt is doing.  But, keep in mind that this code is only clobbering the saltcheck-tests sub-directory of a state being tests.  Or, in the case of highstate testing, the states making up a highstate.

**Comment by mchugh19** [comment]
FYI: it looks like the upstream salt sync isn't quite appropriate due to the assumption of the sync'ed directory starting with an _. But in case it helps, here's the how the sync modules function:

saltutil.sync_beacons: https://github.com/saltstack/salt/blob/develop/salt/modules/saltutil.py#L222-L225
_sync: https://github.com/saltstack/salt/blob/develop/salt/modules/saltutil.py#L98
utils.extmods: https://github.com/saltstack/salt/blob/develop/salt/utils/extmods.py#L40

**Comment by wcannon** [comment]
Interesting.  For now, I'm pretty ok with the way I'm only removing /
copying tst files per state dir.
