### ISSUE TITLE
saltcheck assumes formula contains init.sls

### ISSUE THREAD

**Issue by mchugh19** [wcannon/salt-check#9]
The zabbix state does have a directory structure, but does not contain a init.sls file. Saltcheck seems to assume that init.sls will be iterable. 
```
[DEBUG   ] Could not find file 'salt://zabbix.sls' in saltenv 'base'[DEBUG   ] Could not find file 'salt://zabbix/init.sls' in saltenv 'base'
[DEBUG   ] compile template: False
[ERROR   ] Template was specified incorrectly: False
Passed invalid arguments: string indices must be integers, not str.
```

When creating an empty init.sls, saltcheck shows no results:
```
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/zabbix/init.sls
[DEBUG   ] Template is an empty file: /var/cache/salt/minion/files/base/zabbix/init.sls
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '5fb26463fbe3', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', '5fb26463fbe3', 'tcp://127.0.0.1:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    |_
      ----------
      TEST RESULTS:
          ----------
          Failed:
              0
          Missing Tests:
              0
          Passed:
              0
```

**Comment by wcannon** [comment]
Unfortunately, this is a result of a design choice.   Any state to check with saltcheck must be a valid state implemented as a directory with a valid init.sls file.  An empty init.sls file will not work.

This would work for an init.sls file:

uptime:
  cmd.run


The issue in code that creates this situation is:
def _get_state_sls(state):
    ''' equivalent to a salt cli: salt web state.show_low_sls STATE'''
    sls_list_state = []
    try:
        returned = __salt__['state.show_low_sls'](state)
        for i in returned:
            if i['__sls__'] not in sls_list_state:
                sls_list_state.append(i['__sls__'])
    except Exception:
        raise
    return sls_list_state

This function is called for every state.  Calling this function allows the inclusion of nested states.

**Comment by mchugh19** [comment]
Is it possible to fail gracefully in this case, or to find the saltcheck-test directory for these cases? Some salt forumlas (https://github.com/saltstack-formulas/zabbix-formula) do not include init.sls files. 

Additionally, it seems that if a minion is assigned a sub state, base.common(.init) then the base/saltcheck-test directory is not run in the run_highstate_tests

**Comment by wcannon** [comment]
I need to give the code a review before I can answer that.  I like the idea of failing gracefully, but am not certain if that would cause other issues.

For the sub state question I'm confused on the situation.  Can you give me a clear example?

**Comment by scub** [comment]
I've got a few ideas about how to handle it, assuming I understand the submission correctly. Its the issue we were discussing where `state.show_low_sls` renders includes to the full "path" causing the state directory to be skipped by the [isdir conditional in add_test_files_for_sls](https://github.com/wcannon/salt-check/blob/master/salt/_modules/saltcheck.py#L668) when the include is a state file.

Were likely best off handling this situation when we fail the isdir conditional, moving up a level in the state tree and testing for the saltcheck-tests directory there; we just need to take care to avoid duplicating tests. I've been playing with this idea a bit and will craft the PR for this behavior this weekend.

The following state tree can showcase this behavior better than i'm able to explain it. The `example` state renders out to `example.anything` causing us to miss the saltcheck-tests directory altogether. 

```
./salt/example/init.sls:

include:
  - anything

./salt/example/anything.sls:

simple_nop_state:
  test.nop:
    - name: foo

./salt/example/saltcheck-tests/please.tst:

example_test:
  module_and_function: test.ping
  assertion: assertEqual
  expected-return: True
```

**Comment by wcannon** [comment]
I'm going to run through a few test scenarios on this tomorrow to verify a few assumptions.  But, I had thought (at least it used to be) that in the example above we would pick up the please.tst tests.   

Full disclosure here:  most of my unit tests were written against the assertions cases, not against the test gathering.

**Comment by wcannon** [comment]
Just re-read this thread.  I think there is a little confusion over what "should" happen and what is happening.

Scenario One:  nested states
If a state includes another state and both have saltcheck-tests subdirectories then the tests found in those subdirectories should be added / tested when calling saltcheck.run_state_tests state-A.

Example - nested states:
```
# state-A which has subdir of saltcheck-tests
/srv/salt/state-A/init.sls
  include:
     state-B

# state-B which has subdir of saltcheck-tests
/srv/salt/state-B/init.sls
  apache:
    pkg.installed
```

Scenario Two: state without valid init.sls file
If the call to salt (__salt__['state.show_low_sls'](state)) does not return a valid state then no attempt to collect tests from a subdir of saltcheck-tests will take place

Example - invalid state dir:
```
# state-C - empty/invalid or missing init.sls file, which has subdir of saltcheck-tests
/srv/salt/state-C/init.sls
  # no data - just a comment in init.sls file
```

Scenario Three:  nested state is called directly 
example:  salt srv1 saltcheck.run_state_tests  apache.configs
In this situation the call to __salt__['state.show_low_sls'] will only return the name of apache.confgs and any further nested states, not the parent state(s).  In turn, we only pick up tests from a subdir of the nested state, and any further nested states, skipping the parent states

Example - calling nested state
```
# state-D - nested state is called directly, which has subdir of saltcheck-tests
salt srv1 saltcheck.run_state_tests state-C.configs
Only tests from b.tst will be run by saltcheck
/srv/salt/state-C/
                   |--saltcheck-tests/a.tst
                   |--configs/
                            |--saltcheck-tests/b.tst
```

**Comment by wcannon** [comment]
After reviewing this, and writing it up two things are becoming obvious to me.
1.  I need some very nice functional tests for test gathering
2.  This info needs to be clearly documented in the wiki /  tutorial.  It's a little confusing.
3.  Ideally, examples of all this should be included in the repo for easy experimentation

**Comment by wcannon** [comment]
Committed a fix for this issue.

"The zabbix state does have a directory structure, but does not contain a init.sls file. Saltcheck seems to assume that init.sls will be iterable."
"When creating an empty init.sls, saltcheck shows no results:"

The fix is to simply ignore the inclusion of the state and not raise an error.  Essentially we are failing gracefully in this case.
